//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace outfitters.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public int Id { get; set; }
        public string name { get; set; }
        public Nullable<int> price_ { get; set; }
        public string imgf { get; set; }
        public string imgb { get; set; }
        public Nullable<int> quantity { get; set; }
    }
}
